package de.tu_dresden.lat.Tests;

import com.google.common.collect.Lists;
import com.google.common.collect.Sets;
import de.tu_dresden.inf.lat.model.tools.ToOWLTools;
import de.tu_dresden.lat.data.enums.ExitCode;
import de.tu_dresden.lat.diagnoses.JustificationsGenerator;
import de.tu_dresden.lat.ontologyGenerator.ELOntologyGenerator;
import de.tu_dresden.lat.ontologyGenerator.NameGenerator;
import org.junit.Assert;
import org.junit.Test;
import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.*;

import java.io.File;
import java.util.List;
import java.util.Set;

public class OntologyGeneratorTest {
    private static final OWLOntologyManager manager = OWLManager.createOWLOntologyManager();

    @Test
    public void testELOntologyGenerator() throws OWLOntologyCreationException {
        String lhsStr= "A", rhsStr="C";

        OWLClass lhs = NameGenerator.getInstance().getAsNameGeneratorConceptName(lhsStr);
        OWLClass rhs = NameGenerator.getInstance().getAsNameGeneratorConceptName(rhsStr);

        OWLSubClassOfAxiom axiom = ToOWLTools.getInstance().getOWLSubClassOfAxiom(lhs,rhs);

        ELOntologyGenerator elONtGen = new ELOntologyGenerator(axiom);

        int justTotal = 15, justMaxSize = 10, justMaxCommon = 5;
        String ontologyName = "autoGeneratedELOntology-TEST.owl";

        ExitCode code =  elONtGen.generateOntology(justTotal, justMaxSize, justMaxCommon, ontologyName);

        if(code == ExitCode.terminatedSuccessfully) {
            File ontologyFile = new File(ontologyName);
            OWLOntology ontology = manager.loadOntologyFromOntologyDocument(ontologyFile);

            List<Set<? extends OWLAxiom>> allJustifications =
                    Lists.newLinkedList(JustificationsGenerator.getAllELKJustifications(axiom, ontology));

            Assert.assertEquals(justTotal, allJustifications.size());
            Assert.assertTrue(allJustifications.stream().map(Set::size).noneMatch(x->x>justMaxSize));

            for(int i = 0; i < allJustifications.size() - 1; i++){
                Set<OWLAxiom> intersection = Sets.newHashSet(allJustifications.get(i));
                intersection.retainAll(allJustifications.get(i+1));

                Assert.assertTrue(intersection.size()<=justMaxCommon);
            }
        }

    }
}
