package de.tu_dresden.lat.data.cli;

import de.tu_dresden.inf.lat.counterExample.data.ModelFormat;
import de.tu_dresden.inf.lat.counterExample.data.ModelType;
import de.tu_dresden.inf.lat.evee.data.ProofType;
import de.tu_dresden.lat.data.enums.OutputType;
import de.tu_dresden.lat.data.names.ConcreteDomainName;
import de.tu_dresden.lat.data.names.ReasonerName;

import java.util.Arrays;

/**
 * @author Christian Alrabbaa
 *
 */
public class CLIOptionsDescriptions {
    public static final String
            conclusionAxiomOptionDescription = "Input axiom (in Manchester Syntax)\n",
            ontologyPathOptionDescription = "The path of the ontology file\n",
            outFileLabelOptionDescription = "The label used in naming the generated files\n",
            proofTypeOptionDescription = "Select one of the following proof types " + Arrays.asList(ProofType.values())+"\n",
            outDirOptionDescription = "The directory where to store the generated files\n",
            inputJsonProofPathOptionDescription = "The path of the JSON proof file\n",
            exportMapperOptionDescription = "If a counterexample is generated, the model mapper will be saved to a " +
                    "Json file\n",
            translateAxiom2NLOptionDescription = "By default, every axiom in a proof is associated with an autogenerated " +
            "natural language translation\n",
            generatePNGOptionDescription = "By default, a PNG is created for a generated proof/model\n",
            signatureFilePathOptionDescription = "The path of the signature file\n",
            moduleOptionDescription = "Compute the module of the input axiom, and save it as <label>.owl\n",
            adOptionDescription = "Compute the atomic decomposition of the module of the input axiom\n",
            mDsOptionDescription = "Compute all minimal diagnoses for the provided axiom w.r.t. the provided ontology. " +
            "Optional arguments:\n1- Reasoner name <Hermit> or <Elk>. Default behaviour to exhaust all options \n2- " +
                    "ID to use as a suffix for the output (mds_<ID>.txt). Default is zero\n",
            exampleReasonerOptionDescription = "Generate counter models using tableau-based prover. By default, the counter " +
            "model is generated using ELK\n",
            reasonerNameOptionDescription = "Select one of the following reasoner names " + Arrays.asList(ReasonerName.values()) + ". " +
            "The default is " + CLIOptionsDefaultValues.defaultReasonerStr + ".(This selection affects only CD Proofs)\n",
            concreteDomainNameOptionDescription = "Select one of the following concrete domain names "
            + Arrays.asList(ConcreteDomainName.values())+"\n",
            modelFormatOptionDescription =
                    "Select one of the following model formats " + Arrays.asList(ModelFormat.values())+"\n",
            modelTypeOptionDescription =
                    "Select one of the following model types " + Arrays.asList(ModelType.values())+"\n",
            proofOutTypeOptionDescription =
                    "Select one of the following output types " + Arrays.asList(OutputType.values())+"\n",
            keepGeneratedStuffOptionDescription = "By default, all intermediate files and folder are removed\n",
            constraintsPathOptionDescription = "The path of the concrete domain constraints file\n",
            patternDirOptionDescription = "A JSON file containing a proof pattern\n",
            lemmaTitleOptionDescription = "A label that will be used for the lemma in case of a match in the proof\n",
            diagnosisOptionDescription = "Compute all minimal diagnoses for the provided axiom w.r.t. the provided ontology using the selected reasoner\n",
            repairOptionDescription = "Allow user to navigate and guide through justification selections to compute a repair ontology\n",
            interestingAxiomDescription = "The path of ontology file represting the list of interesting axioms"
    ;
}
